// Régions de Côte d'Ivoire et principales villes par région
export const REGIONS_CI: { name: string; villes: string[] }[] = [
  { name: "Lagunes", villes: ["Abidjan", "Grand-Bassam", "Dabou", "Jacqueville", "Alépé", "Agboville"] },
  { name: "Abidjan", villes: ["Abobo", "Adjamé", "Attécoubé", "Cocody", "Koumassi", "Marcory", "Plateau", "Port-Bouët", "Treichville", "Yopougon"] },
  { name: "Yamoussoukro", villes: ["Yamoussoukro"] },
  { name: "Haut-Sassandra", villes: ["Daloa", "Issia", "Vavoua", "Zoukougbeu"] },
  { name: "Sud-Comoé", villes: ["Aboisso", "Adiaké", "Grand-Bassam", "Tiapoum"] },
  { name: "Worodougou", villes: ["Séguéla", "Kani"] },
  { name: "Sassandra-Marahoué", villes: ["Bouaflé", "Sassandra", "Soubré", "Zuénoula"] },
  { name: "Moronou", villes: ["Bongouanou", "Arrah", "M'Batto"] },
  { name: "N'Zi", villes: ["Dimbokro", "Bocanda", "Kouassi-Kouassikro"] },
  { name: "Marahoué", villes: ["Bouaflé", "Sinfra", "Zuénoula"] },
  { name: "Lôh-Djiboua", villes: ["Divo", "Lakota", "Guitry"] },
  { name: "Kabadougou", villes: ["Odienné", "Madinani", "Samatiguila", "Seguelon"] },
  { name: "Gôh", villes: ["Gagnoa", "Oumé"] },
  { name: "Grands-Ponts", villes: ["Dabou", "Grand-Lahou", "Jacqueville"] },
  { name: "Guémon", villes: ["Duékoué", "Bangolo", "Kouibly"] },
  { name: "Hambol", villes: ["Katiola", "Niakara", "Dabakala"] },
  { name: "Cavally", villes: ["Guiglo", "Bloléquin", "Taï", "Toulepleu"] },
  { name: "Bélier", villes: ["Toumodi", "Djékanou", "Tiébissou"] },
  { name: "Bounkani", villes: ["Bouna", "Doropo", "Nassian", "Téhini"] },
  { name: "Gontougo", villes: ["Bondoukou", "Tanda", "Koun-Fao", "Transua"] },
  { name: "Gbêkê", villes: ["Bouaké", "Béoumi", "Sakassou"] },
  { name: "Iffou", villes: ["Daoukro", "M'Bahiakro", "Prikro"] },
  { name: "Indénié-Djuablin", villes: ["Abengourou", "Agnibilékrou", "Bettié"] },
  { name: "Tchologo", villes: ["Ferkessédougou", "Ouangolodougou", "Kong"] },
  { name: "Poro", villes: ["Korhogo", "M'Bengué", "Dikodougou", "Sinématiali"] },
  { name: "Bagoué", villes: ["Boundiali", "Kouto", "Tengréla"] },
  { name: "Folon", villes: ["Minignan", "Kaniasso"] },
  { name: "Bafing", villes: ["Touba", "Ouaninou", "Koro"] },
  { name: "Tonkpi", villes: ["Man", "Biankouma", "Danané", "Sipilou", "Zouan-Hounien"] },
  { name: "Bère", villes: ["Mankono", "Dianra", "Kounahiri"] },
  { name: "Nawa", villes: ["Soubré", "Buyo", "Méagui"] },
  { name: "San-Pédro", villes: ["San-Pédro", "Tabou", "Grand-Béréby"] },
  { name: "Gbôklé", villes: ["Sassandra", "Fresco"] },
  { name: "La Mé", villes: ["Adzopé", "Afféry", "Akoupé", "Yakassé-Attobrou"] },
  { name: "Agnéby-Tiassa", villes: ["Agboville", "Taabo", "Tiassalé"] },
];

export const SPECIALITES = [
  "Gynécologue",
  "Sage-femme",
  "Pédiatre",
  "Médecin généraliste",
  "Obstétricien",
  "Échographiste",
  "Nutritionniste",
  "Psychologue / Psychiatre",
  "Infirmier",
  "Dermatologue",
  "Dentiste",
  "Radiologue",
  "Anesthésiste",
  "Néonatologiste",
  "Endocrinologue",
  "Kinésithérapeute",
  "Autre",
];

export const TYPES_CONSULTATION = [
  { id: "prenatale", label: "Consultation prénatale", color: "#EC4899" },
  { id: "postnatale", label: "Consultation post-natale", color: "#A855F7" },
  { id: "echographie", label: "Échographie", color: "#06B6D4" },
  { id: "vaccination", label: "Vaccination", color: "#10B981" },
  { id: "pediatrie", label: "Consultation pédiatrique", color: "#3B82F6" },
  { id: "nutrition", label: "Bilan nutritionnel", color: "#84CC16" },
  { id: "contraception", label: "Consultation contraception", color: "#F59E0B" },
  { id: "generale", label: "Consultation générale", color: "#6B7280" },
  { id: "teleconsultation", label: "Téléconsultation", color: "#8B5CF6" },
  { id: "urgence", label: "Urgence / Garde", color: "#EF4444" },
  { id: "accouchement", label: "Accouchement / Suivi travail", color: "#F472B6" },
  { id: "psychologie", label: "Soutien psychologique", color: "#A78BFA" },
];

export const GROUPES_SANGUINS = ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"];
